openapi: 3.0.1

info:
  title: message-board
  description: Public message board service
  version: 1.0.0

servers:
  - url: 'http://localhost'

tags:
  - name: message-board
    description: Public message board service

paths:
  /v1:
    get:
      summary: 'Get all the messages on the board'
      tags:
        - message-board
      operationId: getAllMessages
# TODO: implement pagination
#      parameters:
#        - in: query
#          name: offset
#          description: 'The number of messages to skip'
#          schema:
#            type: integer
#        - in: query
#          name: limit
#          description: 'The number of messages to return'
#          schema:
#            type: integer
      responses:
        200:
          description: 'List of all the messages'
          content:
            application/json:
              schema:
                $ref:
                  '#/components/schemas/messageListDTO'


components:
  schemas:
    userDTO:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    messageDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        text:
          type: string
        userId:
          type: integer
        createdAt:
          type: string
          format: datetime
        updatedAt:
          type: string
          format: datetime
      required:
        - title
        - text

    messageListDTO:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/messageDTO'