openapi: 3.0.1

info:
  title: message-board
  description: Public message board service
  version: 1.0.0

servers:
  - url: 'http://localhost'

tags:
  - name: message-board
    description: Public message board service

paths:
  /v1:
    get:
      summary: 'Hello world'
      description: 'Test'
      tags:
        - message-board
      operationId: getTest
      responses:
        200:
          description: 'All good'
          content:
            application/json:
              schema:
                hello:
                  type: string

components:
  schemas:
    userDTO:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password

    messageDTO:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        text:
          type: string
        userId:
          type: integer
        createdAt:
          type: string
          format: datetime
        updatedAt:
          type: string
          format: datetime
      required:
        - title
        - text
